### ISSUE TITLE
3840x1600

### ISSUE THREAD

**Issue by reosparza** [piittis/witcher-3-ultrawide-cutscene-fix#2]
No option for 38'' ultrawide resolution of 3840x1600

**Comment by piittis** [comment]
PR welcome :)

**Comment by reosparza** [comment]
So no support for that resolution?

**Comment by stevienc** [comment]
Also interested in an option for 3840x1600. 
judging by the last comment, looks like we're on our own to figure it out..

@Dreyarc - I'm not going to bother modifying the code, but i can explain how to do which the author could of just added, or briefly explained without posting a useless comment to tell you to essentially do it yourself.

Use a hex editor I use a program called HxD.

- Open/Edit witcher3.exe in bin\x64 folder (backup the exe if you want to)
- At the top, select **Search** then **Replace**
- Click **Hex-values** tab
- In the **Search for** field enter **39 8E E3 3F**
- In the **Replace with** field enter **9a 99 19 40**
- Select **All** in the Search direction option
- Click **Replace all**
- Save and done

**Comment by piittis** [comment]
Would have been faster to modify the code though, it's not complicated. Cheers @AlexP11223.
